version: "3.8"

services:
  flask_api:
    build: ./flask_api
    container_name: flask_api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build: ./celery_tasks
    container_name: celery_worker
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: celery -A tasks worker --loglevel=info

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask_api
